/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author Ragzard
 */
public class FrmQRClass extends javax.swing.JFrame {

    int xx,xy;
    /**
     * Creates new form FrmQRClass
     */
    public FrmQRClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblImgClass = new javax.swing.JLabel();
        btnReturn = new javax.swing.JLabel();
        ItsonLogo = new javax.swing.JLabel();
        lblClassName = new javax.swing.JLabel();
        lblCodeClass = new javax.swing.JLabel();
        lblHourClass1 = new javax.swing.JLabel();
        decoratorBar = new java.awt.Panel();
        btnExit = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ContentPanel = new java.awt.Panel();
        headerPanel1 = new javax.swing.JPanel();
        lblImgClass1 = new javax.swing.JLabel();
        btnReturn1 = new javax.swing.JLabel();
        ItsonLogo1 = new javax.swing.JLabel();
        lblClassName1 = new javax.swing.JLabel();
        lblCodeClass1 = new javax.swing.JLabel();
        lblHourClass2 = new javax.swing.JLabel();
        imgQR = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        headerPanel.setBackground(new java.awt.Color(2, 24, 133));
        headerPanel.setPreferredSize(new java.awt.Dimension(1000, 120));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImgClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/image.png"))); // NOI18N
        headerPanel.add(lblImgClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 19, -1, -1));

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/btnReturn.png"))); // NOI18N
        btnReturn.setPreferredSize(new java.awt.Dimension(20, 20));
        headerPanel.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, 20, 30));

        ItsonLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/Logo ITSON.png"))); // NOI18N
        headerPanel.add(ItsonLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, -10, -1, -1));

        lblClassName.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblClassName.setForeground(new java.awt.Color(255, 255, 255));
        lblClassName.setText("Nombre alumno");
        headerPanel.add(lblClassName, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 19, -1, -1));

        lblCodeClass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCodeClass.setForeground(new java.awt.Color(255, 255, 255));
        lblCodeClass.setText("01293924");
        headerPanel.add(lblCodeClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 70, 140, -1));

        lblHourClass1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblHourClass1.setForeground(new java.awt.Color(255, 255, 255));
        lblHourClass1.setText("12:00 - 13:00");
        headerPanel.add(lblHourClass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        decoratorBar.setBackground(new java.awt.Color(0, 0, 86));
        decoratorBar.setPreferredSize(new java.awt.Dimension(1000, 35));
        decoratorBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                decoratorBarMousePressed(evt);
            }
        });
        decoratorBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                decoratorBarMouseDragged(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/Exit.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/Minimize.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Control asistencia");

        javax.swing.GroupLayout decoratorBarLayout = new javax.swing.GroupLayout(decoratorBar);
        decoratorBar.setLayout(decoratorBarLayout);
        decoratorBarLayout.setHorizontalGroup(
            decoratorBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decoratorBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 790, Short.MAX_VALUE)
                .addComponent(btnMinimize)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap())
        );
        decoratorBarLayout.setVerticalGroup(
            decoratorBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decoratorBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(decoratorBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decoratorBarLayout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(btnExit)
                        .addContainerGap())
                    .addGroup(decoratorBarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(decoratorBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ContentPanel.setBackground(new java.awt.Color(27, 57, 166));
        ContentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel1.setBackground(new java.awt.Color(2, 24, 133));
        headerPanel1.setPreferredSize(new java.awt.Dimension(1000, 120));
        headerPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImgClass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/image.png"))); // NOI18N
        headerPanel1.add(lblImgClass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 19, -1, -1));

        btnReturn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/btnReturn.png"))); // NOI18N
        btnReturn1.setPreferredSize(new java.awt.Dimension(20, 20));
        headerPanel1.add(btnReturn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, 20, 30));

        ItsonLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/Logo ITSON.png"))); // NOI18N
        headerPanel1.add(ItsonLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, -10, -1, -1));

        lblClassName1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblClassName1.setForeground(new java.awt.Color(255, 255, 255));
        lblClassName1.setText("Nombre clase");
        headerPanel1.add(lblClassName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 19, -1, -1));

        lblCodeClass1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCodeClass1.setForeground(new java.awt.Color(255, 255, 255));
        lblCodeClass1.setText("01293924");
        headerPanel1.add(lblCodeClass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 70, 140, -1));

        lblHourClass2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblHourClass2.setForeground(new java.awt.Color(255, 255, 255));
        lblHourClass2.setText("12:00 - 13:00");
        headerPanel1.add(lblHourClass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        ContentPanel.add(headerPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imgQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QRClassResources/QR.png"))); // NOI18N
        ContentPanel.add(imgQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(26, 42, 97));
        jSeparator1.setForeground(new java.awt.Color(26, 42, 97));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 42, 97)));
        ContentPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 120, 2, 600));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alumnos");
        ContentPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));
        ContentPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 340, 490));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PIN:");
        ContentPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("0000");
        ContentPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alumnos:");
        ContentPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("00");
        ContentPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Presentes:");
        ContentPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 550, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("00");
        ContentPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 550, -1, -1));

        getContentPane().add(ContentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 1000, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        this.dispose();

    }//GEN-LAST:event_btnExitMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void decoratorBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decoratorBarMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_decoratorBarMousePressed

    private void decoratorBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decoratorBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_decoratorBarMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmQRClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmQRClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmQRClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmQRClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmQRClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel ContentPanel;
    private javax.swing.JLabel ItsonLogo;
    private javax.swing.JLabel ItsonLogo1;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JLabel btnReturn;
    private javax.swing.JLabel btnReturn1;
    private java.awt.Panel decoratorBar;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel headerPanel1;
    private javax.swing.JLabel imgQR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblClassName;
    private javax.swing.JLabel lblClassName1;
    private javax.swing.JLabel lblCodeClass;
    private javax.swing.JLabel lblCodeClass1;
    private javax.swing.JLabel lblHourClass1;
    private javax.swing.JLabel lblHourClass2;
    private javax.swing.JLabel lblImgClass;
    private javax.swing.JLabel lblImgClass1;
    // End of variables declaration//GEN-END:variables
}
