/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author Ragzard
 */
public class FrmScanQR extends javax.swing.JFrame {
    
    int xx, xy;

    /**
     * Creates new form FrmScanQR
     */
    public FrmScanQR() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        decoratorBar = new java.awt.Panel();
        btnExit = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ContentPanel = new java.awt.Panel();
        headerPanel = new javax.swing.JPanel();
        lblImgClass = new javax.swing.JLabel();
        btnReturn = new javax.swing.JLabel();
        ItsonLogo = new javax.swing.JLabel();
        lblClassName = new javax.swing.JLabel();
        lblCodeClass = new javax.swing.JLabel();
        lblHourClass1 = new javax.swing.JLabel();
        txtPIN = new javax.swing.JTextField();
        lblScanCam = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        camDecorator = new javax.swing.JLabel();
        camBackground = new javax.swing.JLabel();
        btnCancel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(27, 57, 166));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        decoratorBar.setBackground(new java.awt.Color(0, 0, 86));
        decoratorBar.setPreferredSize(new java.awt.Dimension(1000, 35));
        decoratorBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                decoratorBarMousePressed(evt);
            }
        });
        decoratorBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                decoratorBarMouseDragged(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/Exit.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/Minimize.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Control asistencia");

        javax.swing.GroupLayout decoratorBarLayout = new javax.swing.GroupLayout(decoratorBar);
        decoratorBar.setLayout(decoratorBarLayout);
        decoratorBarLayout.setHorizontalGroup(
            decoratorBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decoratorBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 790, Short.MAX_VALUE)
                .addComponent(btnMinimize)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap())
        );
        decoratorBarLayout.setVerticalGroup(
            decoratorBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decoratorBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(decoratorBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decoratorBarLayout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(btnExit)
                        .addContainerGap())
                    .addGroup(decoratorBarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(decoratorBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ContentPanel.setBackground(new java.awt.Color(27, 57, 166));
        ContentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(2, 24, 133));
        headerPanel.setPreferredSize(new java.awt.Dimension(1000, 120));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImgClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/image.png"))); // NOI18N
        headerPanel.add(lblImgClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 19, -1, -1));

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/btnReturn.png"))); // NOI18N
        btnReturn.setPreferredSize(new java.awt.Dimension(20, 20));
        headerPanel.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, 20, 30));

        ItsonLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/Logo ITSON.png"))); // NOI18N
        headerPanel.add(ItsonLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, -10, -1, -1));

        lblClassName.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblClassName.setForeground(new java.awt.Color(255, 255, 255));
        lblClassName.setText("Nombre alumno");
        headerPanel.add(lblClassName, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 19, -1, -1));

        lblCodeClass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCodeClass.setForeground(new java.awt.Color(255, 255, 255));
        lblCodeClass.setText("01293924");
        headerPanel.add(lblCodeClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 70, 140, -1));

        lblHourClass1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblHourClass1.setForeground(new java.awt.Color(255, 255, 255));
        lblHourClass1.setText("Ing. Software");
        headerPanel.add(lblHourClass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        ContentPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtPIN.setBackground(new java.awt.Color(53, 53, 53));
        txtPIN.setForeground(new java.awt.Color(255, 255, 255));
        txtPIN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPIN.setAutoscrolls(false);
        txtPIN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        txtPIN.setPreferredSize(new java.awt.Dimension(101, 30));
        ContentPanel.add(txtPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 110, -1));

        lblScanCam.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblScanCam.setForeground(new java.awt.Color(255, 255, 255));
        lblScanCam.setText("Escanea el Código QR");
        ContentPanel.add(lblScanCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PIN");
        ContentPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        camDecorator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/Cam decorator.png"))); // NOI18N
        ContentPanel.add(camDecorator, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        camBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/Background.png"))); // NOI18N
        ContentPanel.add(camBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/Cancel btn.png"))); // NOI18N
        ContentPanel.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, -1, -1));

        getContentPane().add(ContentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 1000, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        this.dispose();
      
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void decoratorBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decoratorBarMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_decoratorBarMousePressed

    private void decoratorBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decoratorBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_decoratorBarMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmScanQR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmScanQR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmScanQR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmScanQR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmScanQR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel ContentPanel;
    private javax.swing.JLabel ItsonLogo;
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JLabel btnReturn;
    private javax.swing.JLabel camBackground;
    private javax.swing.JLabel camDecorator;
    private java.awt.Panel decoratorBar;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblClassName;
    private javax.swing.JLabel lblCodeClass;
    private javax.swing.JLabel lblHourClass1;
    private javax.swing.JLabel lblImgClass;
    private javax.swing.JLabel lblScanCam;
    private javax.swing.JTextField txtPIN;
    // End of variables declaration//GEN-END:variables
}
