/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import entidades.Usuario;
import java.awt.Color;

/**
 *
 * @author Ragzard
 */
public class InicioMenu extends javax.swing.JPanel {

    MainWindow mainWindow;
    InicioPanel inicioPanel;
    Usuario usuario;
    int pin;

    Color transparente = new Color(0, 0, 0, 0);
    Color opacidad = new Color(0, 0, 0, 50);

    /**
     *
     * @param mainwindow
     * @param inicioPanel
     * @param usuario
     */
    public InicioMenu(MainWindow mainwindow, InicioPanel inicioPanel, Usuario usuario) {
        initComponents();

        this.usuario = usuario;
        this.mainWindow = mainwindow;
        this.inicioPanel = inicioPanel;

        //this.jLabel1.setBorder(new );
    }

    public int getPin() {
        return pin;
    }

    public void setPin(int pin) {
        this.pin = pin;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAsistencia = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JLabel();
        btnCloseMenu = new javax.swing.JLabel();
        btnCalendario = new javax.swing.JLabel();
        btnClases = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(255, 255, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAsistencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsistenciaMouseClicked(evt);
            }
        });
        add(btnAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, 268, 45));

        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });
        add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 268, 45));

        btnCloseMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloseMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMenuMouseClicked(evt);
            }
        });
        add(btnCloseMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 26, 30, 35));

        btnCalendario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalendarioMouseClicked(evt);
            }
        });
        add(btnCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 268, 45));

        btnClases.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClasesMouseClicked(evt);
            }
        });
        add(btnClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 268, 45));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuAbierto.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsistenciaMouseClicked
        ScanQRPanel scanQR = new ScanQRPanel(mainWindow, inicioPanel, getUsuario());
        scanQR.setPin(pin);
        System.out.println("Se mando el pin: " + pin + " a la clase: " + scanQR.getClass());
        mainWindow.changeContentPane(scanQR);

    }//GEN-LAST:event_btnAsistenciaMouseClicked

    private void btnCloseMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMenuMouseClicked
        inicioPanel.closeMenu();
    }//GEN-LAST:event_btnCloseMenuMouseClicked

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        mainWindow.dispose();
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void btnCalendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalendarioMouseClicked
        // TODO add your handling code here:
        FrmCalendario cale = new FrmCalendario();
        cale.setVisible(true);
        mainWindow.dispose();
    }//GEN-LAST:event_btnCalendarioMouseClicked

    private void btnClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClasesMouseClicked
        // TODO add your handling code here:
        QRClassPanel qrPanel = new QRClassPanel(mainWindow, inicioPanel, usuario);
        mainWindow.changeContentPane(qrPanel);
    }//GEN-LAST:event_btnClasesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAsistencia;
    private javax.swing.JLabel btnCalendario;
    private javax.swing.JLabel btnCerrarSesion;
    private javax.swing.JLabel btnClases;
    private javax.swing.JLabel btnCloseMenu;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
