/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.awt.Color;

/**
 *
 * @author Ragzard
 */
public class InicioMenu extends javax.swing.JPanel {

    MainWindow mainWindow;
    InicioPanel inicioPanel;
    
    Color transparente = new Color(0, 0, 0, 0);
    Color opacidad = new Color(0, 0, 0, 50);

    /**
     * Creates new form InicioMenu
     *
     * @param mainwindow referencia a la ventana principal.
     */
    public InicioMenu(MainWindow mainwindow, InicioPanel inicioPanel) {
        initComponents();

        this.mainWindow = mainwindow;
        this.inicioPanel = inicioPanel;
        
        this.btnAsistencia.setOpaque(false);
        this.btnAsistencia.setBackground(opacidad);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAsistencia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(255, 255, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAsistencia.setBorder(null);
        btnAsistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAsistenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAsistenciaMouseExited(evt);
            }
        });
        add(btnAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, 268, 45));

        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 80, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuAbierto.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsistenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsistenciaMouseEntered
        this.btnAsistencia.setOpaque(true);
    }//GEN-LAST:event_btnAsistenciaMouseEntered

    private void btnAsistenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsistenciaMouseExited
        this.btnAsistencia.setOpaque(false);
    }//GEN-LAST:event_btnAsistenciaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsistencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
