/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import entidades.Usuario;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import subsubsistemaqr.FachadaQR;
import subsubsistemaqr.IQR;

/**
 *
 * @author Ragzard
 */
public class ScanQRPanel extends javax.swing.JPanel {

    MainWindow mainWindow;
    Usuario usuario;
    InicioPanel inicioPanel;

    IQR iqr = new FachadaQR();
    int pin;

    /**
     *
     * @param mainwindow
     * @param inicioPanel
     * @param usuario
     */
    public ScanQRPanel(MainWindow mainwindow, InicioPanel inicioPanel, Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        this.mainWindow = mainwindow;
        this.inicioPanel = inicioPanel;

        lblNombreAlumno.setText(usuario.getNombre());
        lblMatriculaAlumno.setText(String.valueOf(usuario.getMatricula()));
    }

    public int getPin() {
        return pin;
    }

    public void setPin(int pin) {
        this.pin = pin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContentPanel = new java.awt.Panel();
        headerPanel = new javax.swing.JPanel();
        lblImgClass = new javax.swing.JLabel();
        btnReturn = new javax.swing.JLabel();
        ItsonLogo = new javax.swing.JLabel();
        lblNombreAlumno = new javax.swing.JLabel();
        lblMatriculaAlumno = new javax.swing.JLabel();
        txtPIN = new javax.swing.JTextField();
        lblScanCam = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        camDecorator = new javax.swing.JLabel();
        camBackground = new javax.swing.JLabel();
        btnCancel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ContentPanel.setBackground(new java.awt.Color(27, 57, 166));
        ContentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(2, 24, 133));
        headerPanel.setPreferredSize(new java.awt.Dimension(1000, 120));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImgClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/image.png"))); // NOI18N
        headerPanel.add(lblImgClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 19, -1, -1));

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/btnReturn.png"))); // NOI18N
        btnReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReturn.setPreferredSize(new java.awt.Dimension(20, 20));
        btnReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReturnMouseClicked(evt);
            }
        });
        headerPanel.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, 20, 30));

        ItsonLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/Logo ITSON.png"))); // NOI18N
        headerPanel.add(ItsonLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, -10, -1, -1));

        lblNombreAlumno.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblNombreAlumno.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreAlumno.setText("Nombre alumno");
        headerPanel.add(lblNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 19, -1, -1));

        lblMatriculaAlumno.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMatriculaAlumno.setForeground(new java.awt.Color(255, 255, 255));
        lblMatriculaAlumno.setText("01293924");
        headerPanel.add(lblMatriculaAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 140, -1));

        ContentPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtPIN.setBackground(new java.awt.Color(53, 53, 53));
        txtPIN.setForeground(new java.awt.Color(255, 255, 255));
        txtPIN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPIN.setAutoscrolls(false);
        txtPIN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        txtPIN.setPreferredSize(new java.awt.Dimension(101, 30));
        txtPIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPINKeyPressed(evt);
            }
        });
        ContentPanel.add(txtPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 110, -1));

        lblScanCam.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblScanCam.setForeground(new java.awt.Color(255, 255, 255));
        lblScanCam.setText("Escanea el Código QR");
        ContentPanel.add(lblScanCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PIN");
        ContentPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        camDecorator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/Cam decorator.png"))); // NOI18N
        ContentPanel.add(camDecorator, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        camBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/Background.png"))); // NOI18N
        ContentPanel.add(camBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScanQRResources/Cancel btn.png"))); // NOI18N
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        ContentPanel.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, -1, -1));

        add(ContentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseClicked
        mainWindow.changeContentPane(inicioPanel);
    }//GEN-LAST:event_btnReturnMouseClicked

    private void txtPINKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPINKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Aquí pones el código que quieres ejecutar cuando se presiona Enter
            if (Integer.parseInt(txtPIN.getText()) == pin) {
                JOptionPane.showMessageDialog(this, "Se ha registrado su asistencia", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            } else if (txtPIN.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Ingresa el codigo en el campo", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (txtPIN.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingresa el codigo en el campo", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Pin no valido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_txtPINKeyPressed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        mainWindow.changeContentPane(inicioPanel);
    }//GEN-LAST:event_btnCancelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel ContentPanel;
    private javax.swing.JLabel ItsonLogo;
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnReturn;
    private javax.swing.JLabel camBackground;
    private javax.swing.JLabel camDecorator;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblImgClass;
    private javax.swing.JLabel lblMatriculaAlumno;
    private javax.swing.JLabel lblNombreAlumno;
    private javax.swing.JLabel lblScanCam;
    private javax.swing.JTextField txtPIN;
    // End of variables declaration//GEN-END:variables
}
