/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.admin.clases;

import dto.ClaseDTO;
import javax.swing.*;
import subsistemaClases.FachadaClase;
import subsistemaClases.IClase;

/**
 *
 * @author PC
 */
public class FrmModificarClase extends javax.swing.JFrame {

    IClase subsClase = new FachadaClase();
    ClaseDTO claseRecibida = new ClaseDTO();

    /**
     * Creates new form FrmAgregarUsuario
     */
    public FrmModificarClase() {
        initComponents();
    }

    public FrmModificarClase(ClaseDTO claseRecibida) {
        initComponents();
        this.claseRecibida = claseRecibida;

        txtNombre.setText(claseRecibida.getNombre());
        txtSemestre.setText(String.valueOf(claseRecibida.getSemestre()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modificarClase = new javax.swing.JPanel();
        lblModificarClase = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblSemestre = new javax.swing.JLabel();
        txtSemestre = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificarClase.setBackground(new java.awt.Color(27, 57, 166));
        modificarClase.setForeground(new java.awt.Color(27, 57, 166));
        modificarClase.setPreferredSize(new java.awt.Dimension(650, 360));

        lblModificarClase.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblModificarClase.setForeground(new java.awt.Color(255, 255, 255));
        lblModificarClase.setText("Modificar Clase");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");

        lblSemestre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSemestre.setForeground(new java.awt.Color(255, 255, 255));
        lblSemestre.setText("Semestre donde se Imparte:");

        txtSemestre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAceptar.setForeground(new java.awt.Color(0, 0, 0));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modificarClaseLayout = new javax.swing.GroupLayout(modificarClase);
        modificarClase.setLayout(modificarClaseLayout);
        modificarClaseLayout.setHorizontalGroup(
            modificarClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarClaseLayout.createSequentialGroup()
                .addGroup(modificarClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificarClaseLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblNombre))
                    .addGroup(modificarClaseLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificarClaseLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblSemestre))
                    .addGroup(modificarClaseLayout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(btnCancelar)
                        .addGap(34, 34, 34)
                        .addComponent(btnAceptar))
                    .addGroup(modificarClaseLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(txtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarClaseLayout.createSequentialGroup()
                .addComponent(lblModificarClase, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        modificarClaseLayout.setVerticalGroup(
            modificarClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarClaseLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblModificarClase, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addGap(6, 6, 6)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblSemestre)
                .addGap(6, 6, 6)
                .addComponent(txtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(modificarClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar)))
        );

        getContentPane().add(modificarClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        try {
            // Crear el objeto ClaseDTO
            ClaseDTO claseModificada = new ClaseDTO();
            claseModificada.setNombre(txtNombre.getText());
            claseModificada.setSemestre(Integer.parseInt(txtSemestre.getText()));

            // Confirmación en consola (opcional)
            System.out.println("Clase creada para modificar: " + claseModificada);

            subsClase.modificarClase(claseRecibida, claseModificada);

            JOptionPane.showMessageDialog(this, "La clase se ha modificado correctamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            FrmGestionarClase frmGestionarClase = new FrmGestionarClase();
            frmGestionarClase.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error inesperado: " + e, "Ha ocurrido un Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAceptarActionPerformed


    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        FrmGestionarClase gestionarClases = new FrmGestionarClase();
        gestionarClases.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModificarClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModificarClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModificarClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModificarClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModificarClase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblModificarClase;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSemestre;
    private javax.swing.JPanel modificarClase;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSemestre;
    // End of variables declaration//GEN-END:variables
}
