/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.admin.eventos;

import entidades.Evento;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;
import javax.swing.JOptionPane;
import persistencia.FachadaPersistencia;

/**
 *
 * @author limon
 */
public class FrmAgregarEvento extends javax.swing.JFrame {
    
    
    /**
     * Creates new form FrmCalendarioAdmin
     */
    public FrmAgregarEvento() {
        initComponents();
        
        
    }
    
    private void limpiarFormulario() {
        campoTextoTitulo.setText("");
        campoTextoDescripcion.setText("");
        campoDateFechaInicio.setDate(null);
        campoDateFechaFin.setDate(null);
        campoTextoHoraInicio.setText("");
        campoTextoHoraFin.setText("");
        comboBoxCampus.setSelectedIndex(0); // Selecciona el primer elemento
        comboBoxCategoria.setSelectedIndex(0);
    }
    
    public Date convertirFechaAPacifico(Date fecha) {
    // Definir la zona horaria del Pacífico (en este caso, Los Angeles)
    TimeZone pacifico = TimeZone.getTimeZone("America/Los_Angeles");

    // Crear un SimpleDateFormat con el formato solo de fecha (sin la hora)
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    sdf.setTimeZone(pacifico);  // Configura la zona horaria

    // Usar el SimpleDateFormat para formatear la fecha
    String fechaFormateada = sdf.format(fecha);

    try {
        // Convertir la cadena de texto a Date (sin la hora, solo la fecha)
        return sdf.parse(fechaFormateada);
    } catch (Exception e) {
        e.printStackTrace();
    }

    return null;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEventos = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        campoTextoTitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoTextoDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoDateFechaFin = new com.toedter.calendar.JDateChooser();
        campoDateFechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoTextoHoraFin = new javax.swing.JTextField();
        campoTextoHoraInicio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboBoxCampus = new javax.swing.JComboBox<>();
        comboBoxCategoria = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEventos.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        txtEventos.setText("Administrador de Eventos");
        getContentPane().add(txtEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Titulo.setText("Titulo");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));
        getContentPane().add(campoTextoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 220, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Descripcion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));
        getContentPane().add(campoTextoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 220, 80));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Fecha fin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Fecha inicio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));
        getContentPane().add(campoDateFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 90, 30));
        getContentPane().add(campoDateFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 100, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Hora inicio");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Hora fin");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));
        getContentPane().add(campoTextoHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 110, 30));
        getContentPane().add(campoTextoHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 130, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Campus");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Categoria");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, -1, -1));

        comboBoxCampus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nainari", "Centro", "Navojoa", "Empalme" }));
        getContentPane().add(comboBoxCampus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 90, 30));

        comboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recordatorio", "Taller", "Aviso" }));
        comboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 90, 30));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnAgregar.png"))); // NOI18N
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 690, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnCancelar.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 690, -1, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnReturn.png"))); // NOI18N
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrmEvento.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCategoriaActionPerformed

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
        // Recolectar los datos del formulario
        String titulo = campoTextoTitulo.getText();
        String descripcion = campoTextoDescripcion.getText();
        Date fechaInicio = campoDateFechaInicio.getDate(); // Asegúrate de que el componente devuelve un Date
        Date fechaFin = campoDateFechaFin.getDate();
        String horaInicio = campoTextoHoraInicio.getText();
        String horaFin = campoTextoHoraFin.getText();
        String campus = comboBoxCampus.getSelectedItem().toString();
        String categoria = comboBoxCategoria.getSelectedItem().toString();

        // Validar datos
        if (titulo.isEmpty() || descripcion.isEmpty() || fechaInicio == null || fechaFin == null ||
            horaInicio.isEmpty() || horaFin.isEmpty() || campus.isEmpty() || categoria.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convertir las fechas a la zona horaria del Pacífico y quitar la hora
        Date fechaInicioPacifico = convertirFechaAPacifico(fechaInicio);
        Date fechaFinPacifico = convertirFechaAPacifico(fechaFin);

        // Crear el objeto Evento
//        Evento nuevoEvento = new Evento(titulo, descripcion, fechaInicio, fechaFin, horaInicio, horaFin, campus, categoria);
        Evento nuevoEvento = new Evento(titulo, descripcion, fechaInicioPacifico, fechaFinPacifico, horaInicio, horaFin, campus, categoria);

        // Enviar el objeto a la capa de persistencia
        FachadaPersistencia fachada = new FachadaPersistencia();
        fachada.agregarEvento(nuevoEvento);

        // Mostrar mensaje de éxito y limpiar formulario
        JOptionPane.showMessageDialog(this, "Evento agregado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        limpiarFormulario();
        System.out.println("Guardado");
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here
        dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        FrmGestionarEventos fr = new FrmGestionarEventos();
        fr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgregarEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnRegresar;
    private com.toedter.calendar.JDateChooser campoDateFechaFin;
    private com.toedter.calendar.JDateChooser campoDateFechaInicio;
    private javax.swing.JTextField campoTextoDescripcion;
    private javax.swing.JTextField campoTextoHoraFin;
    private javax.swing.JTextField campoTextoHoraInicio;
    private javax.swing.JTextField campoTextoTitulo;
    private javax.swing.JComboBox<String> comboBoxCampus;
    private javax.swing.JComboBox<String> comboBoxCategoria;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel txtEventos;
    // End of variables declaration//GEN-END:variables
}
