/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.admin.eventos;

import dto.EventoDTO;
import java.util.Date;
import javax.swing.JOptionPane;
import persistencia.FachadaPersistencia;

/**
 *
 * @author limon
 */
public class FrmEditarEvento extends javax.swing.JFrame {

   
    
    EventoDTO evento;
    
    /**
     * Creates new form FrmEditarEvento
     */
    public FrmEditarEvento() {
        
    }
    
    public FrmEditarEvento(EventoDTO evento) {
        initComponents();
        
        this.evento = evento;
        mostrarInformacionActualCarrera();
    }

    
    public void mostrarInformacionActualCarrera() {
        campoTextoTitulo.setText(evento.getTitulo());
        campoTextoDescripcion.setText(evento.getDescripcion());
        campoDateFechaInicio.setDate(evento.getFechaInicio());
        campoDateFechaFin.setDate(evento.getFechaFinal()); // Corregido aquí
        campoTextoHoraInicio.setText(evento.getHoraInicio());
        campoTextoHoraFin.setText(evento.getHoraFinal());
        comboBoxCampus.setSelectedItem(evento.getCampus()); // Corregido aquí
        comboBoxCategoria.setSelectedItem(evento.getCategoria()); // Corregido aquí
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxCategoria = new javax.swing.JComboBox<>();
        comboBoxCampus = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        campoTextoHoraInicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoDateFechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        campoTextoDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        campoTextoTitulo = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JLabel();
        campoTextoHoraFin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoDateFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recordatorio", "Taller", "Aviso" }));
        comboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 90, 30));

        comboBoxCampus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nainari", "Centro", "Navojoa", "Empalme" }));
        getContentPane().add(comboBoxCampus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 90, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Campus");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, -1));
        getContentPane().add(campoTextoHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 130, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Hora inicio");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));
        getContentPane().add(campoDateFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 100, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Fecha inicio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));
        getContentPane().add(campoTextoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 220, 80));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Descripcion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Titulo.setText("Titulo");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));
        getContentPane().add(campoTextoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 220, 30));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnCancelar.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 690, -1, -1));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnAgregar.png"))); // NOI18N
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 690, -1, -1));
        getContentPane().add(campoTextoHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 110, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Hora fin");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));
        getContentPane().add(campoDateFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 90, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Fecha fin");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setText("Editar Evento");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrmEvento.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCategoriaActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
       
        String titulo = campoTextoTitulo.getText();
        String descripcion = campoTextoDescripcion.getText(); 
        Date fechaInicio = campoDateFechaInicio.getDate();
        Date fechaFinal = campoDateFechaFin.getDate();
        String horaInicio = campoTextoHoraInicio.getText();
        String horaFinal = campoTextoHoraFin.getText();
        String campus = campoTextoHoraFin.getText();
        String categoria = campoTextoTitulo.getText();
        

        try {

           // Establece los atributos de la carrera
           // Aquí se puede realizar la lógica para guardar o actualizar el evento
        evento.setTitulo(titulo);
        evento.setDescripcion(descripcion);
        evento.setFechaInicio(fechaInicio);
        evento.setFechaFinal(fechaFinal);
        evento.setHoraInicio(horaInicio);
        evento.setHoraFinal(horaFinal);
        evento.setCampus(campus);
        evento.setCategoria(categoria);

            // Inicializa CarreraNegocio y modifica la carrera
            FachadaPersistencia fachada = new FachadaPersistencia();
            fachada.modificarEvento(evento, eventoModificado);

            JOptionPane.showMessageDialog(this, "La Carrera se ha editado correctamente.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            dispose();

        
            JOptionPane.showMessageDialog(this, "El formato del tiempo diario es incorrecto. Use HH:mm:ss.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error inesperado: \n" + e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditarEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnCancelar;
    private com.toedter.calendar.JDateChooser campoDateFechaFin;
    private com.toedter.calendar.JDateChooser campoDateFechaInicio;
    private javax.swing.JTextField campoTextoDescripcion;
    private javax.swing.JTextField campoTextoHoraFin;
    private javax.swing.JTextField campoTextoHoraInicio;
    private javax.swing.JTextField campoTextoTitulo;
    private javax.swing.JComboBox<String> comboBoxCampus;
    private javax.swing.JComboBox<String> comboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
